### ISSUE TITLE
Not compatible with OSV

### ISSUE THREAD

**Issue by nulls** [saveourtool/cosv4k#2]
https://ossf.github.io/osv-schema/#format-overview
> Overall, the approach of this schema is to define only the fields that absolutely must be shared between databases, leaving customizations to the “ecosystem_specific” and “database_specific” blocks (see below)

Looks like the OSV doesn't allow unknown fields in JSON object.

**Comment by akuleshov7** [comment]
Probably it is not a problem, but should be ok

**Comment by akuleshov7** [comment]
As discussed with @nulls - it is not a big problem to extend schema with new fields, should be ok
